allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  core-js: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@filenest-fs/core@0.1.0'
  - '@filenest-fs/node@0.1.1'
  - '@filenest-fs/react@0.1.0'
  - '@filenest-fs/nextjs@0.1.0'
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/engines"
  - "@swc/core"
  - core-js
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
